### ISSUE TITLE
Use Intuition for localisation

### ISSUE THREAD

**Issue by siebrand** [Krinkle/mw-tool-orphantalk#4]
This project is now configured as a separate project at translatewiki.net, but it would be easier to maintain as part of the larger Intuition project. Please update the code to use that framework.

**Comment by Krinkle** [comment]
@siebrand I'm not sure I understand what you mean. This tool already uses Intuition. The store was intentionally separated (in collaboration with @Nikerabbit). The intent it to separate others from Intuition core as well. 

See also:
* https://github.com/Krinkle/intuition/issues/45 (Support storing messages in individual tool repos)
* https://github.com/Krinkle/intuition/wiki/Migrate

**Comment by siebrand** [comment]
Hmm. I unfortunately wasn't made aware of that by @Nikerabbit, @Krinkle. I dislike the additional administrative burden, as these projects are generally very small. It could be considered to move the projects out of Intuition by making all of them a single separate repo that's potentially a submodule of intuition, as is done for Pywikibot.

**Comment by Krinkle** [comment]
@siebrand I'm open to many alternative solutions on the translatewiki.net side. The main problem being addressed with this change is that the source messages should be maintained in the software repository, not elsewhere. Using composer or submodules to pull these in does not scale. Aside from it being an `O(N)` overhead on all tool authors (have to commit to two repos to make changes, have to pull it in to avoid message errors). This makes it impossible to maintain software in a sane way due to there being no atomic way to change or add source messages. It also results in compilation failures due to missing messages (e.g. how do I test against in Jenkins or Travis against a change of the submodule that isn't merged yet).

Imagine MediaWiki core having its en.json files in a separate repository, that would make reviewing and amending changes in Gerrit a nightmare.

All other aspects are negotiable, but I believe I speak for many tool authors when I say that the aspect of the source messages being authored within the relevant Git repository is not negotiable.

**Comment by Nikerabbit** [comment]
While I share Siebrand's concern on additional burden, I also think that not accepting projects in their own repositories will in the long run hurt us more by turning us from a practical solution to irrelevance.
I believe that with this particular issue it is better for us to adapt to changing world, rather than forcing the world to do it our way.

I will continue making the additional burden as small as possible (with all the caveats of limited time etc.) with further automation and streamlining of the process, as well as thinking how we can bring more people to help us.

Siebrand, please accept my apologies for not keeping you in the loop on this topic. I am happy to discuss more.
